DOC-72 changes
StrangeBeeCorp/docs pull request #91
Opened 2024-10-28 09:39 UTC by cybsecmaster

2024-10-28 14:14 UTC, MaelDre commented
How do you access to these guides ?
-> the links "activating license" seems to be broken in the menu:
![image](https://github.com/user-attachments/assets/e50b34df-b467-4487-8e19-658a3b532ecb)

2024-10-29 00:11 UTC, cybsecmaster commented
Added the pages to navigation menu:

![image](https://github.com/user-attachments/assets/e2417045-429c-4e42-99a6-57c9264bde48)

2024-10-30 15:49 UTC, MaelDre requested changes

2024-10-30 15:49 UTC, MaelDre commented on docs/thehive/images/installation/license7.png
Maybe we should remove your personal informations just leave, 
"Welcome", and remove first name/last name on top header bar

2024-10-30 15:49 UTC, MaelDre commented on docs/thehive/images/installation/paid-license-1.png
Same thing, it's better if we can remove my name on the top :)

2024-10-30 15:49 UTC, MaelDre commented on docs/thehive/installation/activate-paid-license.md
> +For full details, refer to [The Hive Pricing](https://strangebee.com/thehive-pricing-on-prem/).
TheHive (without space)

2024-10-30 15:49 UTC, MaelDre commented on docs/thehive/installation/request-community-license.md
> +Starting with TheHive version 5.3, all users are required to generate a valid license to use the platform. Community users can obtain a **free Community License**, while paid licenses (Gold or Platin
functionnalities ? (I'm not sure)

2024-10-30 15:49 UTC, MaelDre commented on docs/thehive/installation/activate-paid-license.md
> +In addition to the [Community License](./request-community-license.md), The Hive provides two advanced licensing options tailored to meet various operational requirements.
TheHive (without space)

2024-11-06 16:34 UTC, cybsecmaster commented on docs/thehive/images/installation/license7.png
This has been completed

2024-11-06 16:34 UTC, cybsecmaster commented on docs/thehive/images/installation/paid-license-1.png
This has been completed

2024-11-06 16:34 UTC, cybsecmaster commented on docs/thehive/installation/activate-paid-license.md
> +For full details, refer to [The Hive Pricing](https://strangebee.com/thehive-pricing-on-prem/).
This has been completed

2024-11-06 16:34 UTC, cybsecmaster commented on docs/thehive/installation/request-community-license.md
> +Starting with TheHive version 5.3, all users are required to generate a valid license to use the platform. Community users can obtain a **free Community License**, while paid licenses (Gold or Platin
This has been completed

2024-11-06 16:34 UTC, cybsecmaster commented on docs/thehive/installation/activate-paid-license.md
> +In addition to the [Community License](./request-community-license.md), The Hive provides two advanced licensing options tailored to meet various operational requirements.
This has been completed

2024-12-10 09:04 UTC, MaelDre approved these changes

2024-12-10 09:05 UTC, MaelDre commented
It looks good to me, but it seems there is a conflict with image directory

2024-12-12 14:05 UTC, merged